version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dhruv_db
      POSTGRES_USER: dhruv_user
      POSTGRES_PASSWORD: dhruv_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dhruv_user -d dhruv_db']
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5.15
    environment:
      NEO4J_AUTH: neo4j/dhruv_pass
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ['CMD', 'cypher-shell', '-u', 'neo4j', '-p', 'dhruv_pass', 'MATCH () RETURN count(*)']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  neo4j_data:
